[simulation]
  name = "turbulence"
  engine = "srpic"
  runtime = 4.0

[grid]
  resolution = [1024,1024]
  extent = [[0.0, 1.0], [0.0, 1.0]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields = [["PERIODIC"], ["PERIODIC"]]
    particles = [["PERIODIC"], ["PERIODIC"]]

[scales]
  larmor0 = 0.0000563819
  skindepth0 = 0.000976563

[algorithms]
  current_filters = 8

  [algorithms.timestep]
    CFL = 0.5

[particles]
  ppc0 = 32.0

  [[particles.species]]
  label = "e-"
  mass = 1.0
  charge = -1.0
  maxnpart = 2e8
  n_payloads = 1

  [[particles.species]]
  label = "e+"
  mass = 1.0
  charge = 1.0
  maxnpart = 2e8
  n_payloads = 1

[setup]
  temperature = 100.0
#  pl_index = -3.0
  machno = 1000.0
  Bnorm = 1.0

[output]
  format = "hdf5"

  [output.fields]
    interval_time = 0.025
    quantities = ["B"]

  [output.particles]
    enable = false

  [output.spectra]
    enable = false
    interval_time = 0.5

[checkpoint]
    interval_time = 1.0
    keep = 0